# Generated by Django 4.2.7 on 2025-05-17 18:18

from django.db import migrations, models
import motion_detector_app.models


class Migration(migrations.Migration):

    dependencies = [
        ('motion_detector_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='videotask',
            name='original_file',
            field=models.FileField(upload_to=motion_detector_app.models.get_upload_path),
        ),
        migrations.AlterField(
            model_name='videotask',
            name='processed_file',
            field=models.FileField(blank=True, null=True, upload_to=motion_detector_app.models.get_processed_path),
        ),
    ]
