# Generated by Django 4.2.7 on 2025-05-17 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('motion_detector_app', '0002_alter_videotask_original_file_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='videotask',
            name='celery_task_id',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='ID задачи Celery'),
        ),
        migrations.AlterField(
            model_name='videotask',
            name='progress',
            field=models.FloatField(default=0, verbose_name='Прогресс выполнения'),
        ),
    ]
