name: Python Checks

on: [push]

jobs:
  code-quality:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.12"]
    steps:
    - uses: actions/checkout@v4
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        persist-credentials: true
      
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
        
    - name: Install dependencies
    run: |
      python -m pip install --upgrade pip
      pip install pylint black opencv-python  # Добавьте сюда все необходимые пакеты

    - name: Auto-format with Black
    run: |
      black $(git ls-files '*.py')  # Форматируем файлы
      git config --global user.name "GitHub Actions"
      git config --global user.email "actions@github.com"
      git add .
      git commit -m "style: apply Black formatting" || echo "Нет изменений для коммита"
      git push

    - name: Analysing the code with pylint
      run: |
        pylint $(git ls-files '*.py')
